### ISSUE TITLE
Increase Zoom levels

### ISSUE THREAD

**Issue by karlbeecken** [jochenklar/fis-broker-proxy#14]
The underlying data for the non-aerial image maps collected from FIS Broker allows for way more details and subsequent zoom levels – see for example the ALKIS map, the proxy only goes up to 19, while I can zoom way more using the FIS Broker website. Is there a specific reason the zoom level stops at 19? And would it be possible to increase the zoom level a bit more? (For my usecase 22 would be great)
![image](https://user-images.githubusercontent.com/32744028/159768516-e4f13f44-09e1-483e-851e-24088e4718aa.png)![image](https://user-images.githubusercontent.com/32744028/159768526-d647536b-1eab-4c03-9b2e-34c807a19cdd.png)

**Comment by tordans** [comment]
We can consider this a more general issue for https://github.com/codeforberlin/mapproxy-config/issues/11. Someone needs to understand how to configure Mapproxy the right way...

If you like, create a few test config entries and we can try them out via screen sharing. 

Here is some info I received as feedback from someone who knows Mapproxy better than me. That should be a good starting point for more research...

> ![image](https://user-images.githubusercontent.com/111561/159774792-16ad9892-8de4-49a8-bdeb-3d2f29ca41dc.jpeg)

**Comment by jochenklar** [comment]
Hey @tordans @karlbeecken , I think we just need to add `num_levels: 22` to the grid option. https://mapproxy.org/docs/nightly/configuration.html#num-levels

**Comment by karlbeecken** [comment]
I think @tordans already tried that in d95f162 and apparently it didn't work

**Comment by tordans** [comment]
Thanks to https://github.com/codeforberlin/mapproxy-config/pull/13#issuecomment-1078889737, all layer now have sharp data at zoom 21.

* Straßenbefahrung zoom 21 https://supaplexosm.github.io/strassenraumkarte-neukoelln/mapproxy_demo_map.html?url=https://mapproxy.codefor.de/tiles/1.0.0/strassenbefahrung/mercator/{z}/{x}/{y}.png#21/52.48131/13.43468
* Alkis zoom 21 https://supaplexosm.github.io/strassenraumkarte-neukoelln/mapproxy_demo_map.html?url=https://mapproxy.codefor.de/tiles/1.0.0/alkis_30/mercator/{z}/{x}/{y}.png#21/52.48150/13.43485
* Berlin Zoom only zoom 20 (the irony ;-)) https://supaplexosm.github.io/strassenraumkarte-neukoelln/mapproxy_demo_map.html?url=https://mapproxy.codefor.de/tiles/1.0.0/zoom/mercator/{z}/{x}/{y}.png#20/52.48146/13.43495
* Trees Zoom 20 https://supaplexosm.github.io/strassenraumkarte-neukoelln/mapproxy_demo_map.html?url=https://mapproxy.codefor.de/tiles/1.0.0/baumbestand_0_1_3_4_merged/mercator/{z}/{x}/{y}.png#21/52.48157/13.43496
* Luftbilder 2020 Zoom 2021 (does not change for 19-21) https://supaplexosm.github.io/strassenraumkarte-neukoelln/mapproxy_demo_map.html?url=https://mapproxy.codefor.de/tiles/1.0.0/2020_true/mercator/{z}/{x}/{y}.png#21/52.48152/13.43475

CC @Wikinaut

**Comment by Wikinaut** [comment]
Ultragreat!

Works, here example of Zoom = 21
https://umap.openstreetmap.fr/de/map/umleitungsplanung-friedenau-v40-21022022_716884#21/52.47722/13.33055

![grafik](https://user-images.githubusercontent.com/1151915/160123259-8c2f7646-7566-48e6-9899-4be017ebbadd.png)

**Comment by Wikinaut** [comment]
![grafik](https://user-images.githubusercontent.com/1151915/160123429-609d80b3-2055-43ea-b158-e007fc79dc0d.png)
