### ISSUE TITLE
Karte für Straßenbeleuchtung fehlt

### ISSUE THREAD

**Issue by ghost** [jochenklar/fis-broker-proxy#15]
https://fbinter.stadt-berlin.de/fb/wms/senstadt/k_oeffbeleucht

**Comment by tordans** [comment]
@Dignusss können wir einfügen, vermutlich. Was ist denn dein Anwendungsfall? 

Interessehalber: hast einen Eindruck von der Aktualität der Daten?

**Comment by tordans** [comment]
@ghost this is not available as https://github.com/codeforberlin/mapproxy-config/tree/master/demo_links#%C3%B6ffentliche-beleuchtung-alkis-berlin-sw

Example https://strassenraumkarte.osm-berlin.org/mapproxy_demo_map/?url=https://mapproxy.codefor.de/tiles/1.0.0/k_oeffbeleucht_alkis/mercator/{z}/{x}/{y}.png#19/52.48166/13.43544
