### ISSUE TITLE
How use it with Mapbox ? 

### ISSUE THREAD

**Issue by CarlosZiegler** [jochenklar/fis-broker-proxy#16]
Hello,

 I am using mapbox and will use it to show some map from Fisbroker into my map. I can ee my map on mapproxy interface:

![image](https://github.com/codeforberlin/mapproxy-config/assets/38855507/281ce75f-5075-43ab-8fc9-7819e704986a)

![image](https://github.com/codeforberlin/mapproxy-config/assets/38855507/34a4d9f1-86ee-4e9b-aba6-ec5661e15014)

This map works :

```javascript
	map.addSource('wms-test-source', {
				type: 'raster',
				tiles: ['https://tiles.codefor.de/berlin-2022-dop20rgbi/{z}/{x}/{y}.png'],
				tileSize: 256
			});
```

![image](https://github.com/codeforberlin/mapproxy-config/assets/38855507/1d3950cf-3db0-40a0-9986-af3d468d3e0d)

But not works locally with tile: `// tiles: ['http://127.0.0.1:8080/tms/bnp_0/webmercator/{z}/{x}/{y}.png'],` or another local.

![image](https://github.com/codeforberlin/mapproxy-config/assets/38855507/27fa7e94-5739-4c94-9160-c8b1cb0c9c3a)

And I have this issues on all layer if try it locally.

Someone can help ?

**Comment by tordans** [comment]
Hey @CarlosZiegler unfortunately I don't know enough bout how this system works to help. I hope you found a solution. I will close this here since it is not directly related to the repo.
