### ISSUE TITLE
Update sources to use new `gdi.berlin.de` source

### ISSUE THREAD

**Issue by tordans** [jochenklar/fis-broker-proxy#17]
The city is working on updating their infrastructure which means we need to update the old `fbintern` urls with new once. And it sounds like we will also need to checkt the layer configuration…

More info in https://www.berlin.de/sen/sbw/_assets/stadtdaten/geoportal/aktuelles/austausch-diente-server-allgemein.pdf?ts=1691689866

> Austausch der Geoportal-Dienste-Server. 
> **Allgemeine Änderungen und Ablauf**
> Wir planen den Austausch unserer Dienste-Server. Dabei werden schrittweise die Geoportal- (FIS- Broker-) Dienste durch Geoportal- (Geoserver-) Dienste ersetzt. Davon betroffen sind die Dienste WMS (WebMapService) und WFS (WebFeatureService). Wie bisher werden dabei die internationalen Anforderungen an die Schnittstelle erfüllt.
> 
> Änderungen beim Umstieg
> - **Rechneradresse WMS**
> aus https://fbinter.stadt-berlin.de/fb/wms/senstadt/ wird https://gdi.berlin.de/services/wms/
> WFS
> aus https://fbinter.stadt-berlin.de/fb/wfs/senstadt/ wird https://gdi.berlin.de/services/wfs/
> - **Name des Layers im WMS**
> Diese waren bisher durchnummeriert. Künftig besteht der Name aus Zeichenfolgen.
> - **Name des FeatureTypes im WFS**
> Der Name des FeatureTypes ändert sich.
> - **Umstrukturierung**
> Bei der Migration wird es voraussichtlich zu Umstrukturierungen bei einigen Diensten kommen (z.B. Entfernen von Beschriftungslayern, Zusammenfassung von Layern, ggf. Abgabe mehrerer FeatureTypes in einem WFS). Zudem wird sich die Reihenfolge der Layer in den Capabilities Responses des WMS ändern. Wenn nicht anders konfiguriert, liefert der Geoserver in alphabetischer Anordnung aus. Der WMS wird einen Rootlayer behalten, dieser wird beim geplanten möglichst einfachen Umstieg nicht mehr abfragbar sein.
> Hinzu kommt beim WMS die Funktion GetFeatureInfo zur Sachdatenanzeige, der WFS kann mehrere FeatureTypes abgeben.
>
> **Zeitliche Planung**
> Die Umstellung wird schrittweise erfolgen, demnächst beginnen und sich über einen längeren Zeitraum erstrecken. Eine genauere Aussage liegt bislang nicht vor.
>
> **Dienst zum Testen**
> An diesen Geoserver-(Internet-) Diensten kann Einbindung vorab probiert werden: Öffentliche Toiletten WMS https://gdi.berlin.de/services/wms/toiletten? Öffentliche Toiletten WFS https://gdi.berlin.de/services/wfs/toiletten?
> 10.8.2023
>       
> Capabilities Requests
> https://gdi.berlin.de/services/wms/toiletten?Request=GetCapabilities&Service=WMS&Version=1.3.0 https://gdi.berlin.de/services/wfs/toiletten?Request=GetCapabilities&Service=WFS&Version=2.0.0
> Bei Fragen wenden Sie sich bitte an III D 1, 90139-5257, renate.zweer@senstadt.berlin.de

---

Ping https://github.com/codeforberlin/luftbilder.berlin.codefor.de/issues/14

**Comment by SupaplexOSM** [comment]
Thats the URL + list of the new layers of Straßenbefahrung 2014:
```
      layers: cm_fahrbahn,cl_gehweg,ck_parkflaeche,cj_fussgaengerzone,ci_oeffentlicher_platz,ch_radweg,cg_baustelle,cf_trennstreifen,ce_gruenflaeche,cd_rampe,cc_treppe,cb_haltestellenwartebereich,ca_haltebereich_bus,bz_gleiskoerper_strab,by_gehwegueberfahrt,bx_fahrbahnschwelle,bw_aufmerksamkeitsfeld,bv_springbrunnen_zierbrunnen,bu_recycling_container,bu1_kleinbauten_sondernutzung,bt_kabelschacht,bs_induktionsschleife,br_fahrgastunterstand,bq_fahrradstaender,bp_fahrbahnmarkierung_flaeche,bo_denkmal,bn_baumscheibe,bm_zugangsbauwerk,bl_strassenentwaesserungsrinne,bk_strassenbegrenzung,bj_sitzbank,bi_schranke,bh_mauer,bg_leitplanke,bf_gelaender,be_fahrbahnmarkierunglinie,bd_bordstein,bc_aufmerksamkeitsstreifen,bb_verkehrsschutzgitter,ba_telefonzelle_telefonstele,az_taxirufsaeule,ay_streugutbehaelter,ax_strassensinkkasten,aw_spielgeraet,av_poller,au_parkscheinautomat,at_mast_lsa,as_mast,ar_kanaldeckel,ar1_kabelkasten,aq_hydrant,ap_handsteuergeraet_lsa,ao_gebaeudeeingang,an_fahrbahnmarkierung_piktogramm,am_fahnenmast,al_durchfahrtshoehe,ak_briefkasten,aj_anlegestelle,ai_anforderungstaster_radverkehr,ah_abfallbehaelter_muellbox,ag_werbesaeule,af_wasserpumpen_brunnen,ae_viz_infotafel,ad_uhr,ac_trinkwasserbrunnen_wasserspender,ab_touchpoint,aa_verkehrszeichen
      url: "https://gdi.berlin.de/services/wms/strassenbefahrung"
```
Can someone please replace this? @tordans @jochenklar

**Comment by tordans** [comment]
This is now done.

All sources have been checked and updated if needed.
In https://github.com/codeforberlin/mapproxy-config/blob/master/layer_comments.yml there is a field `source_check_note` which I used to comment if sources did not change (yet).

**Straßenbefahrung:**
Thanks @SupaplexOSM 
- We have https://github.com/codeforberlin/mapproxy-config/tree/master/demo_links#stra%C3%9Fenbefahrung-2014 now which is what we had before, Straßenbefahrung + a white map
- And now there is https://github.com/codeforberlin/mapproxy-config/tree/master/demo_links#stra%C3%9Fenbefahrung-2014-alkis-berlin-sw which is Straßenbefahrung + Alkis S/W where houses are
- I also updated https://github.com/codeforberlin/mapproxy-config/blob/master/layer_docs/layer_strassenbefahrung_berlin.md to document the layers
- I will update the editor layer index to use the new `+alkis` Version.
